# WM 2nd Turtle Race
import random
import turtle
turtle1 = turtle.Turtle()
turtle2 = turtle.Turtle()
turtle3 = turtle.Turtle()
turtle4 = turtle.Turtle()
turtle5 = turtle.Turtle()
turtle1.penup()
turtle2.penup()
turtle3.penup()
turtle4.penup()
turtle5.penup()
turtle1.shape("turtle")
turtle2.shape("turtle")
turtle3.shape("turtle")
turtle4.shape("turtle")
turtle5.shape("turtle")
turtle1.shapesize(5)
turtle2.shapesize(5)
turtle3.shapesize(5)
turtle4.shapesize(5)
turtle5.shapesize(5)
turtle1.setposition(-1000, 400)
turtle2.setposition(-1000, 200)
turtle3.setposition(-1000, 0)
turtle4.setposition(-1000, -200)
turtle5.setposition(-1000, -400)
turtle.done()